# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/nanoprocessor/.Xil/Vivado-28192-inspiron-5515/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/nano_processor.srcs/sources_1/new/Add_Sub_4.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Monishka_components/Monishka_components.srcs/sources_1/new/D_FF.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Register_Bank/Register_Bank.srcs/sources_1/new/Decoder_2_to_4.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Register_Bank/Register_Bank.srcs/sources_1/new/Decoder_3_to_8.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Monishka_components/Monishka_components.srcs/sources_1/new/FA.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Buses_Package/buses.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Instruction_Decoder/Instruction_Decoder.srcs/sources_1/new/Inst_Decoder.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Monishka_components/Monishka_components.srcs/sources_1/new/Mux_2_way_3_bit.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Mux_2_way_4_bit/Mux_2_way_4_bit.srcs/sources_1/new/Mux_2_way_4_bit.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Mux_8_to_1_4bit/Mux_8_to_1_4bit.srcs/sources_1/new/Mux_8_to_1_4bit.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Monishka_components/Monishka_components.srcs/sources_1/new/Program_Counter.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Program_ROM/Program_ROM.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Monishka_components/Monishka_components.srcs/sources_1/new/RCA_3.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Register_Bank/Register_Bank.srcs/sources_1/new/reg.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Register_Bank/Register_Bank.srcs/sources_1/new/Register_Bank.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Seven_Segment_Display_LUT/7_seg_LUT.srcs/sources_1/new/Seven_seg_LUT.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/repo/Nano-Processor/Slow_Clock/Slow_Clk.vhd}
      {C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/nanoprocessor/nanoprocessor.srcs/sources_1/new/nanoprocessor.vhd}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top nanoprocessor
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Kaveen/Documents/CSE/SEM 2/CS1050 - Computer Oranization and Digital Design/Microprocessor/nanoprocessor/.Xil/Vivado-28192-inspiron-5515/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
